server:
  port: 18880
  servlet:
    context-path: /v1/api

# 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/short-url
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # 404异常配置
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: false


