server:
  port: 18880

# 数据库
spring:
  datasource:
    url: jdbc:mysql://wayok.cn:3306/short_url
    username: root
    password: root12138.
    driver-class-name: com.mysql.jdbc.Driver
  # 404异常配置
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: false

# 未找到后缀信息配置转跳的网站
notfound:
  url: https://google.com


