server:
  port: 18880

# 数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/short_url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 404异常配置
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: false

# 未找到后缀信息配置转跳的网站
notfound:
  url: https://google.com

# 设置前端跳转短链的根域名
root:
  url: https://u.wayok.cn


